# Generated by Django 4.2.1 on 2023-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.BigIntegerField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '1.contactbooks',
                'db_table': 'contactbk_contact',
            },
        ),
    ]
